name: EvokerStaff
version: 1.2
author: smack17
main: org.smack17.EvokerStaff.Main
api-version: 1.16
commands:
  givestaff:
    description: Gives a player the staff
    permission: EvokerStaff.give
permissions:
  EvokerStaff.give:
    description: Give Evoker Staff
    default: op